global:
  scrape_interval:     10s
  evaluation_interval: 10s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'scheduler'
    static_configs:
    - targets: ['scheduler:9090']
